name: 1.1$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPack: 'Application'
  SolutionName: 'MLH.ScreenScraping.sln'

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    name: Azure Pipelines
    vmImage: windows-2019 # note that the Resharper CLT will only work on a windows machine or container
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      SolutionName: $(SolutionName)

  - powershell: |
      $filePath= Join-Path -Path $(Build.Repository.LocalPath) -ChildPath "Sources\Application\Mmu.Mlh.ScreenScraping.nuspec"   
      
      Write-Host "Repository LocalPath: $(Build.Repository.LocalPath)"
      Write-Host "Environment-File: $filePath"
      Write-Host "Build Number: $(Build.BuildNumber	)"
        
      $environmentContent = Get-Content $filePath
      $replaced = $environmentContent -replace '__BuildVersion__', '$(Build.BuildNumber)'
          
      Set-Content -Path $filePath -value $replaced
        
    displayName: 'PowerShell Script'

  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Pack_And_Publish_To_NuGet.yaml@ALMStuff
    parameters:
      FolderToPack: $(FolderToPack)